<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link rel="stylesheet" type="text/css" href="Css/Homecss.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Exo&family=Permanent+Marker&family=Ysabeau+SC&display=swap" rel="stylesheet">
    <meta charset="utf-8" />
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
<footer id="foot">
 © S3944519. ALL RIGHTS RESERVED | DESIGNED FOR INTERNATIONAL MELBOURNE HOTEL
</footer>
</body>
</html>